version: '3.8'

services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    networks:
      - app_network

  client:
    build: ./client
    container_name: client
    restart: always
    environment:
      - API_URL=http://52.28.157.218
    depends_on:
      - backend
    networks:
      - app_network
    ports:
      - "80:80"

  admin:
    build: ./dashboard
    container_name: admin
    restart: always
    environment:
      - API_URL=http://52.28.157.218:81
    depends_on:
      - backend
    networks:
      - app_network
    ports:
      - "81:80"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - backend
      - client
      - admin
    ports:
      - "80:80"
      - "81:81"
      - "5000:5000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
