version: '3.8'
services:
  client:
    build: ./client
    container_name: client
    restart: always
    networks:
      - app-network

  dashboard:
    build: ./dashboard
    container_name: dashboard
    restart: always
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
